{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx-gateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nginx-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nginx-gateway.selectorLabels" . | nindent 6 }}
{{- end }}