apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-user-auth
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-user-auth
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-user-auth
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: DB_HOST
              value: {{ .Release.Name }}-{{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME | quote }}
            - name: AUTH_SERVICE_JWT_ISSUER_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI | quote }}
            - name: AUTH_SERVICE_JWT_JWK_SET_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_JWK_SET_URI | quote }}
            - name: AUTH_SERVICE_TOKEN_URL
              value: {{ .Values.env.AUTH_SERVICE_TOKEN_URL | quote }}
            - name: GATEWAY_URL
              value: {{ .Values.env.GATEWAY_URL | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-user-auth-secret
                  key: DB_PASSWORD
            - name: USER_AUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-user-auth-secret
                  key: USER_AUTH_CLIENT_SECRET
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-user-auth-secret
                  key: JWT_SECRET
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-user-auth-config