apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-auth-service.fullname" . }}
  labels:
    {{- include "user-auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  USER_AUTH_CLIENT_SECRET: {{ .Values.secret.USER_AUTH_CLIENT_SECRET | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | b64enc | quote }}