replicaCount: 1

image:
  repository: cash-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8085

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USERNAME: postgres
  AUTH_SERVICE_JWT_ISSUER_URI:  /serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI:  /serv-auth-service/oauth2/jwks
  AUTH_SERVICE_TOKEN_URL:  /serv-auth-service/oauth2/token
  CASH_CLIENT_SECRET: showcase-secret
  GATEWAY_URL: http://api-gateway-server
  KAFKA_BOOTSTRAP_SERVERS: >-
    microbank-kafka-controller-0.microbank-kafka-controller-headless.dev.svc.cluster.local:9092,
    microbank-kafka-controller-1.microbank-kafka-controller-headless.dev.svc.cluster.local:9092,
    microbank-kafka-controller-2.microbank-kafka-controller-headless.dev.svc.cluster.local:9092

secret:
  DB_PASSWORD: postgres
  CASH_CLIENT_SECRET: showcase-secret

resources: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

fullnameOverride: cash-servicee