apiVersion: v1
kind: Secret
metadata:
  name: transfer-secrets
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc }}
  CLIENT_SECRET: {{ .Values.secrets.CLIENT_SECRET | b64enc }}