apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-account
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Release.Name }}-account
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-account
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-account
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:15-alpine
          command: ['sh', '-c', "until pg_isready -h {{ .Release.Name }}-postgres -p 5432 -U postgres; do echo 'Waiting for postgres...'; sleep 5; done;"]
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: DB_HOST
              value: {{ .Release.Name }}-{{ .Values.env.DB_HOST }}
            - name: DB_PORT
              value: {{ .Values.env.DB_PORT | quote }}
            - name: DB_USERNAME
              value: {{ .Values.env.DB_USERNAME | quote }}
            - name: AUTH_SERVICE_JWT_ISSUER_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI | quote }}
            - name: AUTH_SERVICE_JWT_JWK_SET_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_JWK_SET_URI | quote }}
            - name: APP_CURRENCIES_SUPPORTED
              value: {{ .Values.env.APP_CURRENCIES_SUPPORTED | quote }}
            - name: GATEWAY_URL
              value: {{ .Values.env.GATEWAY_URL | quote }}
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-account-secret
                  key: DB_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-account-config