server:
  port: 8087

exchange:
  rate:
    generation:
      interval:
        ms: 1000

app:
  currencies:
    supported:
      - RUB
      - USD
      - EUR
      - CNY
      - GBP
      - JPY

spring:
  application:
    name: exchange-generator-service

  r2dbc:
    url: ${SPRING_DATASOURCE_URL:r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/exchange_generator_service}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-life-time: 60m
      validation-query: SELECT 1

  scheduling:
    enabled: true
    task:
      scheduling:
        enabled: true

  main:
    web-application-type: reactive

  # ================ OAuth2 Client Configuration ================
  security:
    oauth2:
      # OAuth2 Resource Server Configuration
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVICE_JWT_ISSUER_URI:http://api-gateway-server:8080/serv-auth-service}
          jwk-set-uri: ${AUTH_SERVICE_JWT_JWK_SET_URI:http://api-gateway-server:8080/serv-auth-service/oauth2/jwks}
      # OAuth2 Client Configuration
      client:
        registration:
          exchange-service:
            provider: exchange-service
            client-id: exchange-generator-service
            client-secret: showcase-secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: client_credentials
            scope: exchange-service.read,exchange-service.write
        provider:
          exchange-service:
            token-uri: ${AUTH_SERVICE_TOKEN_URL:http://api-gateway-server:8080/serv-auth-service/oauth2/token}

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework: INFO
    ru.practicum: DEBUG
    org.springframework.cloud.consul: INFO
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
