replicaCount: 1

image:
  repository: notification-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  AUTH_SERVICE_JWT_ISSUER_URI:  /serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI:  /serv-auth-service/oauth2/jwks
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  GATEWAY_URL: http://api-gateway-server
  KAFKA_HOSTS: >-
    microbank-kafka-controller-0.microbank-kafka-controller-headless,
    microbank-kafka-controller-1.microbank-kafka-controller-headless,
    microbank-kafka-controller-2.microbank-kafka-controller-headless

secret:
  MAIL_USERNAME: your-email@gmail.com
  MAIL_PASSWORD: your-app-password

resources: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

fullnameOverride: notification-service