replicaCount: 1
namespace: dev

image:
  repository: notification-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8089

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  AUTH_SERVICE_JWT_ISSUER_URI: http://microbank-gateway:8080/serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI: http://microbank-gateway:8080/serv-auth-service/oauth2/jwks
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: "587"
  GATEWAY_URL: http://microbank-gateway:8080

secret:
  MAIL_USERNAME: your-email@gmail.com
  MAIL_PASSWORD: your-app-password

resources: {}