apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-exchange-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}