apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-notification
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-notification
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-notification
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: AUTH_SERVICE_JWT_ISSUER_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI | quote }}
            - name: AUTH_SERVICE_JWT_JWK_SET_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_JWK_SET_URI | quote }}
            - name: MAIL_HOST
              value: {{ .Values.env.MAIL_HOST | quote }}
            - name: MAIL_PORT
              value: {{ .Values.env.MAIL_PORT | quote }}
            - name: GATEWAY_URL
              value: {{ .Values.env.GATEWAY_URL | quote }}
            - name: MAIL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-notification-secret
                  key: MAIL_USERNAME
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-notification-secret
                  key: MAIL_PASSWORD
          volumeMounts:
            - name: config-volume
              mountPath: /config/application.yml
              subPath: application.yml
              readOnly: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: {{ .Values.service.port }}
            initialDelaySeconds: 20
            periodSeconds: 10
      volumes:
        - name: config-volume
          configMap:
            name: {{ .Release.Name }}-notification-config