apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notification-service.fullname" . }}
  labels:
    {{- include "notification-service.labels" . | nindent 4 }}
type: Opaque
data:
  MAIL_USERNAME: {{ .Values.secret.MAIL_USERNAME | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.secret.MAIL_PASSWORD | b64enc | quote }}