replicaCount: 1

image:
  repository: blocker-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8084

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USERNAME: postgres
  AUTH_SERVICE_JWT_ISSUER_URI:  /serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI:  /serv-auth-service/oauth2/jwks
  BLOCKER_FREQUENCY_THRESHOLD: 5
  BLOCKER_RISK_THRESHOLD: 150
  BLOCKER_DUPLICATE_RISK_SCORE: 100
  BLOCKER_AMOUNT_ANOMALY_RISK_SCORE: 80
  BLOCKER_UNUSUAL_TIME_RISK_SCORE: 70
  BLOCKER_HIGH_FREQUENCY_RISK_SCORE: 90
  BLOCKER_BLOCKED_HISTORY_RISK_SCORE: 50
  GATEWAY_URL: http://api-gateway-server

secret:
  DB_PASSWORD: postgres

resources: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

fullnameOverride: blocker-service