apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-exchange-gen-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  EXCHANGE_GENERATOR_CLIENT_SECRET: {{ .Values.secret.EXCHANGE_GENERATOR_CLIENT_SECRET | b64enc | quote }}