replicaCount: 1
namespace: dev

image:
  repository: exchange-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8086

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USERNAME: postgres
  AUTH_SERVICE_JWT_ISSUER_URI: http://microbank-gateway:8080/serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI: http://microbank-gateway:8080/serv-auth-service/oauth2/jwks
  EXCHANGE_SPREAD: "0.005"
  EXCHANGE_SCALE: "4"
  APP_CURRENCIES_SUPPORTED: "RUB,USD,EUR,CNY,GBP,JPY"
  GATEWAY_URL: http://microbank-gateway:8080

secret:
  DB_PASSWORD: postgres

resources: {}