replicaCount: 1

image:
  repository: exchange-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8086

ingress:
  enabled: false

env:
  SPRING_PROFILES_ACTIVE: prod
  DB_HOST: postgres
  DB_PORT: 5432
  DB_USERNAME: postgres
  AUTH_SERVICE_JWT_ISSUER_URI:  /serv-auth-service
  AUTH_SERVICE_JWT_JWK_SET_URI:  /serv-auth-service/oauth2/jwks
  EXCHANGE_SPREAD: "0.005"
  EXCHANGE_SCALE: "4"
  APP_CURRENCIES_SUPPORTED: "RUB,USD,EUR,CNY,GBP,JPY"
  GATEWAY_URL: http://api-gateway-server
  KAFKA_HOSTS: >-
    microbank-kafka-controller-0.microbank-kafka-controller-headless,
    microbank-kafka-controller-1.microbank-kafka-controller-headless,
    microbank-kafka-controller-2.microbank-kafka-controller-headless

secret:
  DB_PASSWORD: postgres

resources: {}

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

fullnameOverride: exchange-service