apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cash-service.fullname" . }}
  labels:
    {{- include "cash-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  CASH_CLIENT_SECRET: {{ .Values.secret.CASH_CLIENT_SECRET | b64enc | quote }}
