apiVersion: v1
kind: Secret
metadata:
  name: {{ include "front-ui-service.fullname" . }}
  labels:
    {{- include "front-ui-service.labels" . | nindent 4 }}
type: Opaque
data:
  FRONT_CLIENT_SECRET: {{ .Values.secret.FRONT_CLIENT_SECRET | b64enc | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | b64enc | quote }}