apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blocker-service.fullname" . }}
  labels:
    {{- include "blocker-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
