apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-exchange-service
  labels:
    app: exchange-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: exchange-service
  template:
    metadata:
      labels:
        app: exchange-service
    spec:
      containers:
        - name: exchange-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
            - name: SPRING_R2DBC_URL
              value: {{ .Values.env.SPRING_R2DBC_URL | quote }}
            - name: SPRING_R2DBC_USERNAME
              value: {{ .Values.env.SPRING_R2DBC_USERNAME | quote }}
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: exchange-secrets
                  key: DB_PASSWORD
            - name: AUTH_SERVICE_JWT_ISSUER_URI
              value: {{ .Values.env.AUTH_SERVICE_JWT_ISSUER_URI | quote }}
            - name: AUTH_SERVICE_JWK_SET_URI
              value: {{ .Values.env.AUTH_SERVICE_JWK_SET_URI | quote }}
            - name: SPRING_R2DBC_POOL_ENABLED
              value: {{ .Values.env.SPRING_R2DBC_POOL_ENABLED | quote }}
            - name: SPRING_R2DBC_POOL_INITIAL_SIZE
              value: {{ .Values.env.SPRING_R2DBC_POOL_INITIAL_SIZE | quote }}
            - name: SPRING_R2DBC_POOL_MAX_SIZE
              value: {{ .Values.env.SPRING_R2DBC_POOL_MAX_SIZE | quote }}
            - name: SPRING_R2DBC_POOL_MAX_IDLE_TIME
              value: {{ .Values.env.SPRING_R2DBC_POOL_MAX_IDLE_TIME | quote }}
            - name: SPRING_R2DBC_POOL_MAX_LIFE_TIME
              value: {{ .Values.env.SPRING_R2DBC_POOL_MAX_LIFE_TIME | quote }}
            - name: SPRING_R2DBC_POOL_VALIDATION_QUERY
              value: {{ .Values.env.SPRING_R2DBC_POOL_VALIDATION_QUERY | quote }}
          volumeMounts:
            - name: config
              mountPath: /workspace/config
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: exchange-config