apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfer-service.fullname" . }}
  labels:
    {{- include "transfer-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  TRANSFER_CLIENT_SECRET: {{ .Values.secret.TRANSFER_CLIENT_SECRET | b64enc | quote }}