apiVersion: v1
kind: Secret
metadata:
  name: {{ include "serv-auth-service.fullname" . }}
  labels:
    {{- include "serv-auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.secret.CLIENT_SECRET | b64enc | quote }}