apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc | quote }}
  CLIENT_SECRET: {{ .Values.secret.CLIENT_SECRET | b64enc | quote }}